import { Link } from 'react-router-dom';
import { Home, Film, Upload, SearchX, Sparkles } from 'lucide-react';
import { motion } from 'motion/react';
import { Button } from '../components/ui/button.js';
import { Card, CardContent } from '../components/ui/card.js';
import { useLanguage } from '../contexts/LanguageContext.js';
import { Navbar } from '../components/Navbar.js';
import { Footer } from '../components/Footer.js';

export function NotFound() {
  const { language } = useLanguage();

  const suggestions = [
    {
      icon: Home,
      label: language === 'fr' ? 'Retour à l\'accueil' : 'Back to home',
      description: language === 'fr' ? 'Découvrir la galerie de films' : 'Discover the film gallery',
      link: '/',
      color: 'primary'
    },
    {
      icon: Upload,
      label: language === 'fr' ? 'Soumettre un film' : 'Submit a film',
      description: language === 'fr' ? 'Participer au concours' : 'Join the competition',
      link: '/submit',
      color: 'accent'
    },
    {
      icon: Film,
      label: language === 'fr' ? 'S\'inscrire aux événements' : 'Register for events',
      description: language === 'fr' ? 'Réserver vos places' : 'Reserve your seats',
      link: '/login',
      color: 'primary'
    }
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      
      <main className="flex-1 container mx-auto px-4 py-12 md:py-20 mt-[60px] flex items-center justify-center" role="main">
        <div className="max-w-4xl w-full text-center">
          {/* Animated 404 */}
          <motion.div
            initial={{ opacity: 0, y: -30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="mb-8"
          >
            <div className="relative inline-block">
              {/* Glowing 404 */}
              <h1 className="text-[120px] md:text-[200px] font-bold leading-none">
                <span className="bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent animate-pulse">
                  404
                </span>
              </h1>
              
              {/* Floating particles */}
              <motion.div
                animate={{
                  y: [0, -10, 0],
                  rotate: [0, 5, -5, 0]
                }}
                transition={{
                  duration: 3,
                  repeat: Infinity,
                  ease: "easeInOut"
                }}
                className="absolute -top-8 -right-8"
              >
                <Sparkles className="w-12 h-12 md:w-16 md:h-16 text-accent" aria-hidden="true" />
              </motion.div>
              
              <motion.div
                animate={{
                  y: [0, 10, 0],
                  rotate: [0, -5, 5, 0]
                }}
                transition={{
                  duration: 2.5,
                  repeat: Infinity,
                  ease: "easeInOut",
                  delay: 0.5
                }}
                className="absolute -bottom-4 -left-8"
              >
                <Sparkles className="w-8 h-8 md:w-12 md:h-12 text-primary" aria-hidden="true" />
              </motion.div>
            </div>
          </motion.div>

          {/* Message */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mb-12"
          >
            <div className="flex items-center justify-center gap-3 mb-4">
              <SearchX className="w-8 h-8 md:w-10 md:h-10 text-muted-foreground" aria-hidden="true" />
              <h2 className="text-2xl md:text-4xl font-bold">
                {language === 'fr' ? 'Page Non Trouvée' : 'Page Not Found'}
              </h2>
            </div>
            <p className="text-base md:text-lg text-muted-foreground max-w-2xl mx-auto">
              {language === 'fr' 
                ? 'Désolé, la page que vous recherchez semble avoir été générée par une IA un peu trop créative... Elle n\'existe pas !'
                : 'Sorry, the page you\'re looking for seems to have been generated by a slightly too creative AI... It doesn\'t exist!'}
            </p>
          </motion.div>

          {/* Suggestions Grid */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6 mb-8"
          >
            {suggestions.map((suggestion, index) => {
              const Icon = suggestion.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.5 + index * 0.1 }}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <Link to={suggestion.link}>
                    <Card className={`
                      border-${suggestion.color}/30 
                      bg-${suggestion.color}/5 
                      hover:border-${suggestion.color}/50 
                      transition-all cursor-pointer h-full
                      group
                    `}>
                      <CardContent className="p-6 text-center">
                        <div className={`
                          w-14 h-14 rounded-full 
                          bg-${suggestion.color}/20 
                          flex items-center justify-center 
                          mx-auto mb-4
                          group-hover:bg-${suggestion.color}/30
                          transition-colors
                        `}>
                          <Icon className={`w-7 h-7 text-${suggestion.color}`} aria-hidden="true" />
                        </div>
                        <h3 className="font-semibold text-base md:text-lg mb-2">
                          {suggestion.label}
                        </h3>
                        <p className="text-sm text-muted-foreground">
                          {suggestion.description}
                        </p>
                      </CardContent>
                    </Card>
                  </Link>
                </motion.div>
              );
            })}
          </motion.div>

          {/* Primary CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.8 }}
          >
            <Link to="/">
              <Button 
                size="lg" 
                className="bg-accent text-accent-foreground hover:bg-accent/90 shadow-lg shadow-accent/30 transition-all"
                aria-label={language === 'fr' ? 'Retour à l\'accueil' : 'Back to home'}
              >
                <Home className="w-5 h-5 mr-2" aria-hidden="true" />
                {language === 'fr' ? 'Retour à l\'Accueil' : 'Back to Home'}
              </Button>
            </Link>
          </motion.div>

          {/* Fun fact */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 1.2 }}
            className="mt-12 p-4 rounded-lg bg-card/30 border border-border/50 backdrop-blur-sm"
          >
            <p className="text-sm text-muted-foreground italic">
              {language === 'fr' 
                ? '💡 Le saviez-vous ? Cette page 404 a été conçue avec autant de soin que nos films générés par IA !'
                : '💡 Did you know? This 404 page was designed with as much care as our AI-generated films!'}
            </p>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
