import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.admin': 'Administration',
    'nav.submit': 'Soumettre un Film',
    'nav.jury': 'Interface Jury',
    'nav.gallery': 'Galerie',
    'nav.back': 'Retour',
    'nav.language': 'Sélectionner la langue',
    
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.loading': 'Chargement...',
    'common.required': 'Obligatoire',
    'common.optional': 'Optionnel',
    'common.search': 'Rechercher...',
    'common.filter': 'Filtrer',
    'common.clear': 'Effacer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.validated': 'Validé',
    'common.pending': 'En attente',
    'common.rejected': 'Rejeté',
    
    // Landing Page
    'landing.title': 'marsAI',
    'landing.subtitle': 'Festival de Courts-Métrages IA',
    'landing.edition': 'Marseille 2026',
    'landing.theme': 'Thème : \"Imaginer des Futurs Désirables\"',
    'landing.theme.description': 'Explorez l\'avenir à travers le prisme de l\'intelligence artificielle. Découvrez comment les créateurs du monde entier imaginent des mondes meilleurs grâce à l\'IA.',
    'landing.hero.title': 'L\'imaginaire n\'a plus de limites. L\'IA a trouvé sa scène.',
    'landing.hero.subtitle': 'Découvrez les futurs souhaitables à travers l\'œil des créateurs et la puissance de l\'intelligence artificielle.',
    'landing.submit.cta': 'Soumettre un Chef-d\'œuvre',
    'landing.explore.cta': 'Explorer la Galerie 2026',
    'landing.program': 'Programme du Festival',
    'landing.search.placeholder': 'Rechercher un film...',
    'landing.filters.title': 'Filtres',
    'landing.filters.selection': 'Sélection',
    'landing.filters.official': 'Sélection Officielle Uniquement',
    'landing.filters.aitools': 'Outils IA Utilisés',
    'landing.filters.country': 'Pays',
    'landing.filters.countries': 'Pays',
    'landing.results': 'films',
    'landing.results.showing': 'Affichage de',
    'landing.results.of': 'sur',
    'landing.results.none': 'Aucun film ne correspond à vos filtres.',
    
    // AI Tools
    'ai.script': 'Scénario',
    'ai.image': 'Image',
    'ai.video': 'Vidéo',
    'ai.sound': 'Son',
    
    // Admin Dashboard
    'admin.title': 'Tableau de Bord Super Admin',
    'admin.festival.instance': 'Instance du Festival',
    'admin.festival.switch': 'Changer d\'édition du festival',
    'admin.stats.films': 'Films au Total',
    'admin.stats.countries': 'Pays Représentés',
    'admin.stats.rating': 'Note Moyenne',
    'admin.stats.selection': 'Sélection Officielle',
    'admin.branding.title': 'Configuration de l\'Identité',
    'admin.branding.description': 'Personnalisez l\'identité visuelle',
    'admin.branding.logo': 'Logo du Festival',
    'admin.branding.logo.hint': 'PNG ou SVG recommandé, max 2MB',
    'admin.branding.color': 'Couleur Principale',
    'admin.branding.youtube': 'Clé API YouTube',
    'admin.branding.youtube.hint': 'Requis pour l\'intégration vidéo',
    'admin.settings.title': 'Paramètres du Festival',
    'admin.settings.start': 'Date d\'Ouverture des Soumissions',
    'admin.settings.end': 'Date de Clôture',
    'admin.settings.duration': 'Durée Max du Film (secondes)',
    'admin.users.title': 'Gestion des Utilisateurs',
    'admin.users.jury': 'Membres du Jury',
    'admin.users.add': 'Ajouter un Membre',
    'admin.tabs.branding': 'Identité',
    'admin.tabs.settings': 'Paramètres',
    'admin.tabs.users': 'Utilisateurs',
    
    // Submission Form
    'submit.title': 'Soumission de Film',
    'submit.hero.title': 'Devenez l\'architecte du monde de demain.',
    'submit.step': 'Étape',
    'submit.progress': 'Progression',
    'submit.step1.title': 'Identité',
    'submit.step1.description': 'Vos informations personnelles',
    'submit.step1.firstname': 'Prénom',
    'submit.step1.lastname': 'Nom',
    'submit.step1.age': 'Âge',
    'submit.step1.age.error': 'Vous devez avoir au moins 18 ans',
    'submit.step1.email': 'Email',
    'submit.step1.role': 'Rôle Professionnel',
    'submit.step1.role.placeholder': 'Réalisateur, Artiste, Développeur...',
    'submit.step1.social': 'Réseaux Sociaux',
    'submit.step2.title': 'Données du Film',
    'submit.step2.description': 'Informations sur votre œuvre',
    'submit.step2.title.fr': 'Titre (Français)',
    'submit.step2.title.en': 'Titre (Anglais)',
    'submit.step2.duration': 'Durée (secondes)',
    'submit.step2.duration.error': 'Le film doit faire 60 secondes maximum',
    'submit.step2.synopsis.fr': 'Synopsis (Français)',
    'submit.step2.synopsis.en': 'Synopsis (Anglais)',
    'submit.step2.synopsis.placeholder': 'Décrivez votre film...',
    'submit.step2.chars': 'caractères',
    'submit.step3.title': 'Déclaration IA',
    'submit.step3.description': 'Racontez-nous votre collaboration avec la machine.',
    'submit.step3.type': 'Type d\'Utilisation',
    'submit.step3.type.100': '100% Généré par IA',
    'submit.step3.type.hybrid': 'Hybride (IA + Humain)',
    'submit.step3.techstack': 'Stack Technique IA',
    'submit.step3.techstack.placeholder': 'Listez les outils utilisés (ex: Midjourney, Runway, GPT-4...)',
    'submit.step3.methodology': 'Méthodologie Créative',
    'submit.step3.methodology.placeholder': 'Décrivez votre processus créatif...',
    'submit.step4.title': 'Médias',
    'submit.step4.description': 'Fichiers et contenus multimédias',
    'submit.step4.youtube': 'URL YouTube',
    'submit.step4.youtube.hint': 'Téléversez votre film sur YouTube (non listé ou public)',
    'submit.step4.poster': 'Affiche du Film',
    'submit.step4.poster.hint': 'Format JPG, max 2MB',
    'submit.step4.subtitles': 'Fichier de Sous-titres',
    'submit.step4.subtitles.hint': 'Format SRT',
    'submit.step5.title': 'Équipe',
    'submit.step5.description': 'Collaborateurs et équipe',
    'submit.step5.collaborators': 'Membres de l\'Équipe',
    'submit.step5.add': 'Ajouter un Collaborateur',
    'submit.step5.collaborator': 'Collaborateur',
    'submit.step5.name': 'Nom',
    'submit.step5.role': 'Rôle',
    'submit.step5.role.placeholder': 'Co-réalisateur, Designer sonore...',
    'submit.step5.email': 'Email',
    'submit.success': 'Votre film a été soumis avec succès !',
    'submit.final': 'Soumettre le Film',
    'submit.final.ready': 'Prêt à marquer l\'histoire du cinéma génératif ?',
    'submit.previous': 'Précédent',
    'submit.next': 'Suivant',
    'submit.submit': 'Soumettre le Film',
    'submit.validation.error': 'Veuillez remplir tous les champs obligatoires avant de continuer.',
    
    // Jury Interface
    'jury.title': 'Interface Jury marsAI',
    'jury.subtitle': 'Espace d\'Évaluation Professionnel',
    'jury.progress': 'Progression',
    'jury.progress.films': 'films évalués',
    'jury.nav.previous': 'Film Précédent',
    'jury.nav.next': 'Film Suivant',
    'jury.film': 'Film',
    'jury.film.of': 'sur',
    'jury.video.title': 'Projection du Film',
    'jury.video.duration': 'Durée',
    'jury.video.director': 'Réalisateur',
    'jury.video.replay': 'Rejouer',
    'jury.video.fullscreen': 'Plein Écran',
    'jury.ai.title': 'Carte d\'Identité IA',
    'jury.ai.description': 'Outils et méthodologie utilisés',
    'jury.ai.script': 'Génération de Scénario',
    'jury.ai.image': 'Génération d\'Images',
    'jury.ai.video': 'Génération Vidéo',
    'jury.ai.sound': 'Son & Musique',
    'jury.ai.notused': 'Non utilisé',
    'jury.ai.methodology': 'Méthodologie Créative',
    'jury.rating.title': 'Votre Évaluation',
    'jury.rating.subtitle': 'Règle des 3',
    'jury.rating.received': 'évaluations reçues',
    'jury.rating.score': 'Note',
    'jury.rating.poor': 'Faible',
    'jury.rating.average': 'Moyen',
    'jury.rating.excellent': 'Excellent',
    'jury.rating.comments': 'Commentaires Internes Privés',
    'jury.rating.comments.placeholder': 'Partagez vos réflexions pour la délibération...',
    'jury.rating.comments.hint': 'Ces commentaires sont confidentiels',
    'jury.rating.submit': 'Soumettre l\'Évaluation',
    'jury.rating.submitted': 'Évaluation Soumise',
    
    // Badges
    'badge.official': 'Sélection Officielle',
    
    // Footer
    'footer.tagline': 'Propulser le cinéma de demain, aujourd\'hui.',
    'footer.navigation': 'Navigation',
    'footer.gallery': 'Galerie',
    'footer.submit': 'Soumettre',
    'footer.jury': 'Jury',
    'footer.legal': 'Légal',
    'footer.legal.notice': 'Mentions Légales',
    'footer.privacy': 'Confidentialité',
    'footer.gdpr': 'RGPD',
    'footer.status': 'Statut',
    'footer.status.operational': 'Systèmes Opérationnels',
    'footer.copyright': 'Tous droits réservés.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.admin': 'Administration',
    'nav.submit': 'Submit a Film',
    'nav.jury': 'Jury Interface',
    'nav.gallery': 'Gallery',
    'nav.back': 'Back',
    'nav.language': 'Select Language',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.validated': 'Validated',
    'common.pending': 'Pending',
    'common.rejected': 'Rejected',
    
    // Landing Page
    'landing.title': 'marsAI',
    'landing.subtitle': 'AI Short Film Festival',
    'landing.edition': 'Marseille 2026',
    'landing.theme': 'Theme: "Imagining Desirable Futures"',
    'landing.theme.description': 'Explore the future through the lens of artificial intelligence. Discover how creators worldwide imagine better worlds with AI.',
    'landing.hero.title': 'Imagination knows no bounds. AI has found its stage.',
    'landing.hero.subtitle': 'Discover desirable futures through the eyes of creators and the power of artificial intelligence.',
    'landing.submit.cta': 'Submit a Masterpiece',
    'landing.explore.cta': 'Explore the 2026 Gallery',
    'landing.program': 'Festival Program',
    'landing.search.placeholder': 'Search films...',
    'landing.filters.title': 'Filters',
    'landing.filters.selection': 'Selection',
    'landing.filters.official': 'Official Selection Only',
    'landing.filters.aitools': 'AI Tools Used',
    'landing.filters.country': 'Country',
    'landing.filters.countries': 'Countries',
    'landing.results': 'films',
    'landing.results.showing': 'Showing',
    'landing.results.of': 'of',
    'landing.results.none': 'No films match your filters.',
    
    // AI Tools
    'ai.script': 'Script',
    'ai.image': 'Image',
    'ai.video': 'Video',
    'ai.sound': 'Sound',
    
    // Admin Dashboard
    'admin.title': 'Super Admin Dashboard',
    'admin.festival.instance': 'Festival Instance',
    'admin.festival.switch': 'Switch between festival editions',
    'admin.stats.films': 'Total Films',
    'admin.stats.countries': 'Countries',
    'admin.stats.rating': 'Avg Rating',
    'admin.stats.selection': 'Official Selection',
    'admin.branding.title': 'Branding Configuration',
    'admin.branding.description': 'Customize visual identity',
    'admin.branding.logo': 'Festival Logo',
    'admin.branding.logo.hint': 'PNG or SVG recommended, max 2MB',
    'admin.branding.color': 'Primary Color',
    'admin.branding.youtube': 'YouTube API Key',
    'admin.branding.youtube.hint': 'Required for video integration',
    'admin.settings.title': 'Festival Settings',
    'admin.settings.start': 'Submission Start Date',
    'admin.settings.end': 'Submission End Date',
    'admin.settings.duration': 'Max Film Duration (seconds)',
    'admin.users.title': 'User Management',
    'admin.users.jury': 'Jury Members',
    'admin.users.add': 'Add Member',
    'admin.tabs.branding': 'Branding',
    'admin.tabs.settings': 'Settings',
    'admin.tabs.users': 'Users',
    
    // Submission Form
    'submit.title': 'Film Submission',
    'submit.hero.title': 'Be the architect of tomorrow\'s world.',
    'submit.step': 'Step',
    'submit.progress': 'Progress',
    'submit.step1.title': 'Identity',
    'submit.step1.description': 'Your personal information',
    'submit.step1.firstname': 'First Name',
    'submit.step1.lastname': 'Last Name',
    'submit.step1.age': 'Age',
    'submit.step1.age.error': 'You must be at least 18 years old',
    'submit.step1.email': 'Email',
    'submit.step1.role': 'Professional Role',
    'submit.step1.role.placeholder': 'Director, Artist, Developer...',
    'submit.step1.social': 'Social Media',
    'submit.step2.title': 'Film Data',
    'submit.step2.description': 'Information about your work',
    'submit.step2.title.fr': 'Title (French)',
    'submit.step2.title.en': 'Title (English)',
    'submit.step2.duration': 'Duration (seconds)',
    'submit.step2.duration.error': 'Film must be 60 seconds or less',
    'submit.step2.synopsis.fr': 'Synopsis (French)',
    'submit.step2.synopsis.en': 'Synopsis (English)',
    'submit.step2.synopsis.placeholder': 'Describe your film...',
    'submit.step2.chars': 'characters',
    'submit.step3.title': 'AI Declaration',
    'submit.step3.description': 'Tell us about your collaboration with the machine.',
    'submit.step3.type': 'Usage Type',
    'submit.step3.type.100': '100% AI Generated',
    'submit.step3.type.hybrid': 'Hybrid (AI + Human)',
    'submit.step3.techstack': 'AI Tech Stack',
    'submit.step3.techstack.placeholder': 'List tools used (e.g., Midjourney, Runway, GPT-4...)',
    'submit.step3.methodology': 'Creative Methodology',
    'submit.step3.methodology.placeholder': 'Describe your creative process...',
    'submit.step4.title': 'Media',
    'submit.step4.description': 'Files and multimedia content',
    'submit.step4.youtube': 'YouTube URL',
    'submit.step4.youtube.hint': 'Upload your film to YouTube (unlisted or public)',
    'submit.step4.poster': 'Film Poster',
    'submit.step4.poster.hint': 'JPG format, max 2MB',
    'submit.step4.subtitles': 'Subtitles File',
    'submit.step4.subtitles.hint': 'SRT format',
    'submit.step5.title': 'Team',
    'submit.step5.description': 'Collaborators and team',
    'submit.step5.collaborators': 'Team Members',
    'submit.step5.add': 'Add Collaborator',
    'submit.step5.collaborator': 'Collaborator',
    'submit.step5.name': 'Name',
    'submit.step5.role': 'Role',
    'submit.step5.role.placeholder': 'Co-director, Sound designer...',
    'submit.step5.email': 'Email',
    'submit.success': 'Your film has been submitted successfully!',
    'submit.final': 'Submit Film',
    'submit.final.ready': 'Ready to mark the history of generative cinema?',
    'submit.previous': 'Previous',
    'submit.next': 'Next',
    'submit.submit': 'Submit Film',
    'submit.validation.error': 'Please fill in all required fields before continuing.',
    
    // Jury Interface
    'jury.title': 'marsAI Jury Interface',
    'jury.subtitle': 'Professional Evaluation Workspace',
    'jury.progress': 'Progress',
    'jury.progress.films': 'films rated',
    'jury.nav.previous': 'Previous Film',
    'jury.nav.next': 'Next Film',
    'jury.film': 'Film',
    'jury.film.of': 'of',
    'jury.video.title': 'Film Screening',
    'jury.video.duration': 'Duration',
    'jury.video.director': 'Director',
    'jury.video.replay': 'Replay',
    'jury.video.fullscreen': 'Fullscreen',
    'jury.ai.title': 'AI Identity Card',
    'jury.ai.description': 'Tools and methodology used',
    'jury.ai.script': 'Script Generation',
    'jury.ai.image': 'Image Generation',
    'jury.ai.video': 'Video Generation',
    'jury.ai.sound': 'Sound & Music',
    'jury.ai.notused': 'Not used',
    'jury.ai.methodology': 'Creative Methodology',
    'jury.rating.title': 'Your Rating',
    'jury.rating.subtitle': 'Rule of 3',
    'jury.rating.received': 'ratings received',
    'jury.rating.score': 'Score',
    'jury.rating.poor': 'Poor',
    'jury.rating.average': 'Average',
    'jury.rating.excellent': 'Excellent',
    'jury.rating.comments': 'Private Internal Comments',
    'jury.rating.comments.placeholder': 'Share your thoughts for deliberation...',
    'jury.rating.comments.hint': 'These comments are confidential',
    'jury.rating.submit': 'Submit Rating',
    'jury.rating.submitted': 'Rating Submitted',
    
    // Badges
    'badge.official': 'Official Selection',
    
    // Footer
    'footer.tagline': 'Propelling tomorrow\'s cinema, today.',
    'footer.navigation': 'Navigation',
    'footer.gallery': 'Gallery',
    'footer.submit': 'Submit',
    'footer.jury': 'Jury',
    'footer.legal': 'Legal',
    'footer.legal.notice': 'Legal Notice',
    'footer.privacy': 'Privacy',
    'footer.gdpr': 'GDPR',
    'footer.status': 'Status',
    'footer.status.operational': 'Systems Operational',
    'footer.copyright': 'All rights reserved.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialiser avec la langue sauvegardée dans localStorage ou 'fr' par défaut
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('marsai-language');
    return (savedLanguage === 'en' || savedLanguage === 'fr') ? savedLanguage : 'fr';
  });

  // Sauvegarder la langue dans localStorage à chaque changement
  useEffect(() => {
    localStorage.setItem('marsai-language', language);
    // Également mettre à jour l'attribut lang du document HTML pour l'accessibilité
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}